export default {
    loading: false,
    languages: [],
    courseList: [],
    courseTypeList: [],
    subjectList: [],
    boardList: [],
    standardList: [],
    difficultyList: [],
    typeList: [],
    typeListParagraph: [],
    inquirySources: [],
    inquiryFollowupTypes: [],
    inquiryAssignees: [],
    inquiryStatus: [],
    feeTypesList: [],
    documentTypesList: [],
    standardSectionList: [],
}
